name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Cookiecutter Package
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ['3.10',  '3.11', '3.12']
    steps:
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Cookiecutter
        run: pip install cookiecutter
      - name: Generate project
        run: cookiecutter --no-input .
      - name: Install new project
        run: pip install ./custom_codemod
      - name: Run codemodder
        run: codemodder --list
